{:spans
 [{:id "T25",
   :type :edu.upc.atdlib.span/Action,
   :start 1636,
   :end 1646,
   :text "prescribes"}
  {:id "T4",
   :type :edu.upc.atdlib.span/Action,
   :start 256,
   :end 265,
   :text "fills out"}
  {:id "T7",
   :type :edu.upc.atdlib.span/Action,
   :start 424,
   :end 433,
   :text "fills out"}
  {:id "T17",
   :type :edu.upc.atdlib.span/Action,
   :start 1306,
   :end 1315,
   :text "validates"}
  {:id "T21",
   :type :edu.upc.atdlib.span/Action,
   :start 1536,
   :end 1545,
   :text "validates"}
  {:id "T0",
   :type :edu.upc.atdlib.span/Action,
   :start 100,
   :end 108,
   :text "examined"}
  {:id "T12",
   :type :edu.upc.atdlib.span/Action,
   :start 780,
   :end 788,
   :text "arranges"}
  {:id "T13",
   :type :edu.upc.atdlib.span/Action,
   :start 993,
   :end 1001,
   :text "prepared"}
  {:id "T16",
   :type :edu.upc.atdlib.span/Action,
   :start 1204,
   :end 1212,
   :text "conducts"}
  {:id "T1",
   :type :edu.upc.atdlib.span/Action,
   :start 141,
   :end 148,
   :text "decides"}
  {:id "T9",
   :type :edu.upc.atdlib.span/Action,
   :start 624,
   :end 631,
   :text "informs"}
  {:id "T5",
   :type :edu.upc.atdlib.span/Action,
   :start 383,
   :end 389,
   :text "placed"}
  {:id "T14",
   :type :edu.upc.atdlib.span/Action,
   :start 1110,
   :end 1115,
   :text "takes"}
  {:id "T15",
   :type :edu.upc.atdlib.span/Action,
   :start 1150,
   :end 1155,
   :text "sends"}
  {:id "T23",
   :type :edu.upc.atdlib.span/Action,
   :start 1612,
   :end 1617,
   :text "makes"}
  {:id "T11",
   :type :edu.upc.atdlib.span/Condition,
   :start 671,
   :end 750,
   :text
   "the patient signs an informed consent and agrees to continue with the procedure"}
  {:id "T20",
   :type :edu.upc.atdlib.span/Condition,
   :start 1393,
   :end 1440,
   :text "it is contaminated and a new sample is required"}
  {:id "T3",
   :type :edu.upc.atdlib.span/Condition,
   :start 175,
   :end 219,
   :text "needs to undertake an additional examination"}
  {:id "T19",
   :type :edu.upc.atdlib.span/Condition,
   :start 1346,
   :end 1381,
   :text "the sample can be used for analysis"}
  {:id "T2",
   :type :edu.upc.atdlib.span/Condition,
   :start 157,
   :end 171,
   :text "she is healthy"}
  {:id "T6",
   :type :edu.upc.atdlib.span/Entity,
   :start 338,
   :end 379,
   :text "examination and follow-up treatment order"}
  {:id "T36",
   :type :edu.upc.atdlib.span/Entity,
   :start 754,
   :end 779,
   :text "delegate of the physician"}
  {:id "T34",
   :type :edu.upc.atdlib.span/Entity,
   :start 965,
   :end 989,
   :text "examination and sampling"}
  {:id "T39",
   :type :edu.upc.atdlib.span/Entity,
   :start 644,
   :end 665,
   :text "about potential risks"}
  {:id "T33",
   :type :edu.upc.atdlib.span/Entity,
   :start 1116,
   :end 1136,
   :text "the sample requested"}
  {:id "T38",
   :type :edu.upc.atdlib.span/Entity,
   :start 603,
   :end 623,
   :text "outpatient physician"}
  {:id "T44",
   :type :edu.upc.atdlib.span/Entity,
   :start 115,
   :end 135,
   :text "outpatient physician"}
  {:id "T32",
   :type :edu.upc.atdlib.span/Entity,
   :start 1217,
   :end 1236,
   :text "follow-up treatment"}
  {:id "T42",
   :type :edu.upc.atdlib.span/Entity,
   :start 270,
   :end 287,
   :text "examination form"}
  {:id "T30",
   :type :edu.upc.atdlib.span/Entity,
   :start 1095,
   :end 1109,
   :text "ward physician"}
  {:id "T37",
   :type :edu.upc.atdlib.span/Entity,
   :start 789,
   :end 803,
   :text "an appointment"}
  {:id "T8",
   :type :edu.upc.atdlib.span/Entity,
   :start 436,
   :end 448,
   :text "request form"}
  {:id "T24",
   :type :edu.upc.atdlib.span/Entity,
   :start 1622,
   :end 1631,
   :text "diagnosis"}
  {:id "T27",
   :type :edu.upc.atdlib.span/Entity,
   :start 1571,
   :end 1580,
   :text "physician"}
  {:id "T28",
   :type :edu.upc.atdlib.span/Entity,
   :start 1285,
   :end 1294,
   :text "physician"}
  {:id "T40",
   :type :edu.upc.atdlib.span/Entity,
   :start 397,
   :end 406,
   :text "physician"}
  {:id "T41",
   :type :edu.upc.atdlib.span/Entity,
   :start 246,
   :end 255,
   :text "physician"}
  {:id "T26",
   :type :edu.upc.atdlib.span/Entity,
   :start 1651,
   :end 1658,
   :text "therapy"}
  {:id "T43",
   :type :edu.upc.atdlib.span/Entity,
   :start 89,
   :end 96,
   :text "patient"}
  {:id "T29",
   :type :edu.upc.atdlib.span/Entity,
   :start 1320,
   :end 1325,
   :text "state"}
  {:id "T35",
   :type :edu.upc.atdlib.span/Entity,
   :start 1007,
   :end 1012,
   :text "nurse"}],
 :relations
 [{:id "R1",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T23",
   :dst "T24"}
  {:id "R2",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T25",
   :dst "T26"}
  {:id "R3",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T23",
   :dst "T27"}
  {:id "R4",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T25",
   :dst "T27"}
  {:id "R5",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T17",
   :dst "T28"}
  {:id "R6",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T17",
   :dst "T29"}
  {:id "R7",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T15",
   :dst "T30"}
  {:id "R9",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T14",
   :dst "T30"}
  {:id "R10",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T16",
   :dst "T30"}
  {:id "R11",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T16",
   :dst "T32"}
  {:id "R12",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T14",
   :dst "T33"}
  {:id "R13",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T15",
   :dst "T33"}
  {:id "R14",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T13",
   :dst "T35"}
  {:id "R15",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T13",
   :dst "T34"}
  {:id "R16",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T12",
   :dst "T37"}
  {:id "R17",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T12",
   :dst "T36"}
  {:id "R18",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T9",
   :dst "T39"}
  {:id "R19",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T9",
   :dst "T38"}
  {:id "R20",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T5",
   :dst "T6"}
  {:id "R21",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T5",
   :dst "T40"}
  {:id "R22",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T7",
   :dst "T40"}
  {:id "R23",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T7",
   :dst "T8"}
  {:id "R24",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T4",
   :dst "T42"}
  {:id "R25",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T4",
   :dst "T41"}
  {:id "R26",
   :type :edu.upc.atdlib.relation/Patient,
   :src "T0",
   :dst "T43"}
  {:id "R27",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T0",
   :dst "T44"}
  {:id "R28",
   :type :edu.upc.atdlib.relation/Agent,
   :src "T1",
   :dst "T44"}
  {:id "R30",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T0",
   :dst "T1"}
  {:id "R31",
   :type :edu.upc.atdlib.relation/Alternatives,
   :src "T0",
   :dst ["T4" "T5"]}
  {:id "R32",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T5",
   :dst "T7"}
  {:id "R33",
   :type :edu.upc.atdlib.relation/Precedence,
   :src ["T9"],
   :dst "T11"}
  {:id "R33",
   :type :edu.upc.atdlib.relation/Mandatory,
   :src "T11",
   :dst "T11"}
  {:id "R34",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T11",
   :dst "T12"}
  {:id "R34",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T12",
   :dst "T13"}
  {:id "R35",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T13",
   :dst "T14"}
  {:id "R36",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T14",
   :dst "T15"}
  {:id "R37",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T14",
   :dst "T16"}
  {:id "R38",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T15",
   :dst "T17"}
  {:id "R31",
   :type :edu.upc.atdlib.relation/Alternatives,
   :src "T17",
   :dst ["T19" "T20"]}
  {:id "R40",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T21",
   :dst "T23"}
  {:id "R41",
   :type :edu.upc.atdlib.relation/Sequence,
   :src "T21",
   :dst "T25"}
  {:id "R42",
   :type :edu.upc.atdlib.relation/Terminating,
   :src "T19",
   :dst "T19"}
  {:id "R60",
   :type :edu.upc.atdlib.relation/LoopBack,
   :src "T20",
   :dst "T12"}],
 :attributes [],
 :scopes
 [{:id "P0",
   :activities
   #{"T11" "T13" "T9" "T25" "T12" "T23" "T3" "T7" "T16" "T0" "T2" "T14"
     "T15" "T17" "T21" "T20" "T5" "T19" "T4" "T1"}}
  {:id "P1", :activities #{"T3" "T7" "T0" "T2" "T5" "T4" "T1"}}
  {:id "P23",
   :activities
   #{"T11" "T13" "T9" "T12" "T16" "T14" "T15" "T17" "T20" "T19"}}
  {:id "P2", :activities #{"T9"}}
  {:id "P3",
   :activities
   #{"T11" "T13" "T12" "T16" "T14" "T15" "T17" "T20" "T19"}}
  {:id "P4", :activities #{"T25" "T23" "T21"}}],
 :scope-relations
 [{:id "PR1",
   :type :edu.upc.atdlib.scope-relation/Sequential,
   :src "P1",
   :dst "P23"}
  {:id "PR2",
   :type :edu.upc.atdlib.scope-relation/Sequential,
   :src "P2",
   :dst "P3"}
  {:id "PR2",
   :type :edu.upc.atdlib.scope-relation/Iterating,
   :src "P3",
   :dst "P3"}
  {:id "PR6",
   :type :edu.upc.atdlib.scope-relation/Sequential,
   :src "P23",
   :dst "P4"}
  {:id "PR8",
   :type :edu.upc.atdlib.scope-relation/Mandatory,
   :src "P1",
   :dst "P1"}
  {:id "PR9",
   :type :edu.upc.atdlib.scope-relation/Mandatory,
   :src "P2",
   :dst "P2"}
  {:id "PR10",
   :type :edu.upc.atdlib.scope-relation/Mandatory,
   :src "P3",
   :dst "P3"}
  {:id "PR11",
   :type :edu.upc.atdlib.scope-relation/Mandatory,
   :src "P4",
   :dst "P4"}
  {:id "PR12",
   :type :edu.upc.atdlib.scope-relation/Mandatory,
   :src "P23",
   :dst "P23"}]}
